name: rrptflutter
description: A new Flutter application.
version: 1.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.16.1
  flutter_localizations:
    sdk: flutter


  flutter_signin_button: ^1.0.0
  http: 0.12.1
  json_annotation: 3.1.0
  fluttertoast: 4.0.1
  cupertino_icons: ^0.1.2
  url_launcher: 5.5.0
  flutter_spinkit: ^4.1.2
  share: 0.6.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.1
  flutter_linkify: ^3.1.3
  font_awesome_flutter: ^8.5.0
  shared_preferences: 0.5.8
  firebase_admob: 0.9.3+2
  firebase_core: 0.4.5
  splashscreen:
  #  dash_chat: 1.1.15
  flutter_chat_bubble: 1.0.2

dev_dependencies:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.0

flutter_launcher_name:
  name: "Raj Rajedra Prakashan Trust"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/

  fonts:

    - family: ManropeBold
      fonts:
        - asset: fonts/manrope-bold.otf
    - family: ManropMedium
      fonts:
        - asset: fonts/manrope-medium.otf
    - family: ManropRegular
      fonts:
        - asset: fonts/manrope-regular.otf
    - family: ManropSemiBold
      fonts:
        - asset: fonts/manrope-semibold.otf

      #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
