name: rrptflutter
description: A new Flutter application.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  http: 0.12.0+4
  json_annotation: 3.0.1
  fluttertoast: 4.0.1
  cupertino_icons: ^0.1.2
  url_launcher: 5.4.5
  flutter_spinkit: ^4.1.2
  share: 0.6.4


dev_dependencies:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "rrpt"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/img1.jpg
    - assets/icon/icon.png


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
