name: rrptflutter
description: A new Flutter application.
version: 1.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  for internationlization
  intl: 0.16.1
  flutter_localizations:
    sdk: flutter

  #  different signin button
  flutter_signin_button: ^1.0.0

  http: 0.12.1

  #  for create models
  json_annotation: 3.1.0
  #  flutter packages pub run build_runner build
  #  flutter packages pub run build_runner build --delete-conflicting-outputs

  fluttertoast: 4.0.1
  cupertino_icons: ^0.1.2
  url_launcher: 5.5.0
  flutter_spinkit: ^4.1.2
  share: 0.6.4+3

  #  google login
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.1
  firebase_admob: 0.9.3+2
  firebase_core: 0.4.5
  #  sign_in_with_apple: 2.5.2

  # create clickable text for link finder
  flutter_linkify: ^3.1.3

  # provide different icons
  font_awesome_flutter: ^8.5.0

  #  provide google fonts
  #  google_fonts: 1.1.0

  # check internet connectivity
  #  connectivity: 0.4.9+3

  shared_preferences: 0.5.8

  #  get file location from device
  #  path_provider: 1.6.18

  # for splash screen
  splashscreen:

  #  for chat ui
  #  dash_chat: 1.1.15
  flutter_chat_bubble: 1.0.2

  #  state management
  #  rxdart: 0.24.1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5

dev_dependencies:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.0

flutter_launcher_name:
  name: "Raj Rajedra Prakashan Trust"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/

  fonts:
    - family: ManropeBold
      fonts:
        - asset: fonts/manrope-bold.otf
    - family: ManropMedium
      fonts:
        - asset: fonts/manrope-medium.otf
    - family: ManropRegular
      fonts:
        - asset: fonts/manrope-regular.otf
    - family: ManropSemiBold
      fonts:
        - asset: fonts/manrope-semibold.otf

flutter_intl:
  main_locale: en_US
  enabled: true
